---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: hello-world
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
    # fluxcd.io/tag.chart-image: semver:~5.0
spec:
  releaseName: hello-world
  chart:
    git: git@github.com:ziraldo-oanda/hello-world
    path: chart/hello-world
    ref: master
